# action.yml
name: compile mbed projects
author: oclyke-actions
description: compile mbed projects
inputs:
  jobs:
    description: serialized json array with entries [{"name":\ "[job-name", "loc":\ "[job-location]", "cmd":\ "[job command]"}, ...]
    required: true
    default: '{}'
  mbed:
    description: the url for the git repo containing the mbed version to use
    required: false
    default: 'https://github.com/ARMmbed/mbed-os'
outputs:
  jobs:
    description: serialized json object with reults of jobs
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mbed }}
    - ${{ inputs.jobs }}